// flow-typed signature: 791aadf1fb4a53a9cd27c2e96ba8d1c4
// flow-typed version: <<STUB>>/bulma_v^0.7.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
