// flow-typed signature: f8a9c2e072716a7e6d49867b8767fd53
// flow-typed version: <<STUB>>/can-use-dom_v^0.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'can-use-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'can-use-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'can-use-dom/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'can-use-dom/index' {
  declare module.exports: $Exports<'can-use-dom'>;
}
declare module 'can-use-dom/index.js' {
  declare module.exports: $Exports<'can-use-dom'>;
}
declare module 'can-use-dom/test.js' {
  declare module.exports: $Exports<'can-use-dom/test'>;
}
