// flow-typed signature: c0994a19e4d0b79c5da22fa749272e60
// flow-typed version: <<STUB>>/disqus-react_v^1.0.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'disqus-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'disqus-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'disqus-react/dist/index' {
  declare module.exports: any;
}

declare module 'disqus-react/dist/index.min' {
  declare module.exports: any;
}

declare module 'disqus-react/lib/CommentCount' {
  declare module.exports: any;
}

declare module 'disqus-react/lib/CommentEmbed' {
  declare module.exports: any;
}

declare module 'disqus-react/lib/DiscussionEmbed' {
  declare module.exports: any;
}

declare module 'disqus-react/lib/index' {
  declare module.exports: any;
}

declare module 'disqus-react/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'disqus-react/dist/index.js' {
  declare module.exports: $Exports<'disqus-react/dist/index'>;
}
declare module 'disqus-react/dist/index.min.js' {
  declare module.exports: $Exports<'disqus-react/dist/index.min'>;
}
declare module 'disqus-react/lib/CommentCount.js' {
  declare module.exports: $Exports<'disqus-react/lib/CommentCount'>;
}
declare module 'disqus-react/lib/CommentEmbed.js' {
  declare module.exports: $Exports<'disqus-react/lib/CommentEmbed'>;
}
declare module 'disqus-react/lib/DiscussionEmbed.js' {
  declare module.exports: $Exports<'disqus-react/lib/DiscussionEmbed'>;
}
declare module 'disqus-react/lib/index.js' {
  declare module.exports: $Exports<'disqus-react/lib/index'>;
}
declare module 'disqus-react/lib/utils.js' {
  declare module.exports: $Exports<'disqus-react/lib/utils'>;
}
