// flow-typed signature: a14dcac60d1b8c0ea14284ddcfd414d2
// flow-typed version: <<STUB>>/gatsby-transformer-sharp_v^2.1.1-beta.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-transformer-sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-transformer-sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-transformer-sharp/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/on-node-create' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/on-node-create' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/types' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-transformer-sharp/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/extend-node-type'>;
}
declare module 'gatsby-transformer-sharp/fragments.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/fragments'>;
}
declare module 'gatsby-transformer-sharp/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/gatsby-node'>;
}
declare module 'gatsby-transformer-sharp/index' {
  declare module.exports: $Exports<'gatsby-transformer-sharp'>;
}
declare module 'gatsby-transformer-sharp/index.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp'>;
}
declare module 'gatsby-transformer-sharp/on-node-create.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/on-node-create'>;
}
declare module 'gatsby-transformer-sharp/src/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/extend-node-type'>;
}
declare module 'gatsby-transformer-sharp/src/fragments.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/fragments'>;
}
declare module 'gatsby-transformer-sharp/src/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/gatsby-node'>;
}
declare module 'gatsby-transformer-sharp/src/on-node-create.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/on-node-create'>;
}
declare module 'gatsby-transformer-sharp/src/types.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/types'>;
}
declare module 'gatsby-transformer-sharp/types.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/types'>;
}
