// flow-typed signature: af2d6e12ba57ec1358e2bbffd4cf501c
// flow-typed version: <<STUB>>/gatsby-plugin-algolia_v0.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-algolia'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-algolia' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-algolia/example/gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-algolia/example/src/components/header' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-algolia/example/src/layouts/index' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-algolia/example/src/pages/404' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-algolia/example/src/pages/index' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-algolia/example/src/pages/page-2' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-algolia/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-algolia/example/gatsby-config.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/example/gatsby-config'>;
}
declare module 'gatsby-plugin-algolia/example/src/components/header.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/example/src/components/header'>;
}
declare module 'gatsby-plugin-algolia/example/src/layouts/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/example/src/layouts/index'>;
}
declare module 'gatsby-plugin-algolia/example/src/pages/404.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/example/src/pages/404'>;
}
declare module 'gatsby-plugin-algolia/example/src/pages/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/example/src/pages/index'>;
}
declare module 'gatsby-plugin-algolia/example/src/pages/page-2.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/example/src/pages/page-2'>;
}
declare module 'gatsby-plugin-algolia/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/gatsby-node'>;
}
declare module 'gatsby-plugin-algolia/index' {
  declare module.exports: $Exports<'gatsby-plugin-algolia'>;
}
declare module 'gatsby-plugin-algolia/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia'>;
}
