// flow-typed signature: e1e847af449786dc01975eb42c1274ee
// flow-typed version: <<STUB>>/gatsby-plugin-styled-components_v^3.0.0-beta.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-styled-components/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-styled-components/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-styled-components/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-styled-components/gatsby-node'>;
}
declare module 'gatsby-plugin-styled-components/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-styled-components/gatsby-ssr'>;
}
declare module 'gatsby-plugin-styled-components/index' {
  declare module.exports: $Exports<'gatsby-plugin-styled-components'>;
}
declare module 'gatsby-plugin-styled-components/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-styled-components'>;
}
