// flow-typed signature: ce7d48e89cdd091de1619ec1a5eaa407
// flow-typed version: <<STUB>>/gatsby-plugin-algolia_v0.0.4/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-algolia'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-algolia' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-algolia/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-algolia/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia/gatsby-node'>;
}
declare module 'gatsby-plugin-algolia/index' {
  declare module.exports: $Exports<'gatsby-plugin-algolia'>;
}
declare module 'gatsby-plugin-algolia/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-algolia'>;
}
