// flow-typed signature: b30f92db3529b3e7b795b5a7485eb303
// flow-typed version: <<STUB>>/gatsby-plugin-webpack-size_v0.0.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-webpack-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-webpack-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-webpack-size/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-webpack-size/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-webpack-size/gatsby-node'>;
}
declare module 'gatsby-plugin-webpack-size/index' {
  declare module.exports: $Exports<'gatsby-plugin-webpack-size'>;
}
declare module 'gatsby-plugin-webpack-size/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-webpack-size'>;
}
