// flow-typed signature: 23318ee8bea916c202a59e15edf4b630
// flow-typed version: <<STUB>>/gatsby-plugin-netlify_v^2.0.0-beta.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-netlify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-netlify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-netlify/build-headers-program' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-netlify/constants' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-netlify/create-redirects' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-netlify/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-netlify/plugin-data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-netlify/build-headers-program.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify/build-headers-program'>;
}
declare module 'gatsby-plugin-netlify/constants.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify/constants'>;
}
declare module 'gatsby-plugin-netlify/create-redirects.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify/create-redirects'>;
}
declare module 'gatsby-plugin-netlify/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify/gatsby-node'>;
}
declare module 'gatsby-plugin-netlify/index' {
  declare module.exports: $Exports<'gatsby-plugin-netlify'>;
}
declare module 'gatsby-plugin-netlify/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify'>;
}
declare module 'gatsby-plugin-netlify/plugin-data.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify/plugin-data'>;
}
