// flow-typed signature: 186c874f472ac454371571816fcb292e
// flow-typed version: <<STUB>>/gatsby-plugin-netlify-cms_v^2.0.0-beta.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-netlify-cms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-netlify-cms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-netlify-cms/cms' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-netlify-cms/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-netlify-cms/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-netlify-cms/cms.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cms/cms'>;
}
declare module 'gatsby-plugin-netlify-cms/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cms/gatsby-browser'>;
}
declare module 'gatsby-plugin-netlify-cms/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cms/gatsby-node'>;
}
declare module 'gatsby-plugin-netlify-cms/index' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cms'>;
}
declare module 'gatsby-plugin-netlify-cms/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-netlify-cms'>;
}
