// flow-typed signature: 177823a9a4205c818870d4c0f05c0a0a
// flow-typed version: <<STUB>>/gatsby-plugin-manifest_v^2.0.2-rc.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-manifest/common' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-manifest/common.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/common'>;
}
declare module 'gatsby-plugin-manifest/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/gatsby-node'>;
}
declare module 'gatsby-plugin-manifest/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/gatsby-ssr'>;
}
declare module 'gatsby-plugin-manifest/index' {
  declare module.exports: $Exports<'gatsby-plugin-manifest'>;
}
declare module 'gatsby-plugin-manifest/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest'>;
}
