// flow-typed signature: 2cb8a6cfea37f3b7948d65f9e7b9b547
// flow-typed version: <<STUB>>/gatsby-transformer-yaml_v^2.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-transformer-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-transformer-yaml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-transformer-yaml/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-transformer-yaml/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-yaml/gatsby-node'>;
}
declare module 'gatsby-transformer-yaml/index' {
  declare module.exports: $Exports<'gatsby-transformer-yaml'>;
}
declare module 'gatsby-transformer-yaml/index.js' {
  declare module.exports: $Exports<'gatsby-transformer-yaml'>;
}
