// flow-typed signature: cb1a429359cdd4f9c2a488e22e5cf314
// flow-typed version: <<STUB>>/gatsby-plugin-sitemap_v^2.0.0-beta.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-sitemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-sitemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-sitemap/__tests__/index' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sitemap/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sitemap/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sitemap/internals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-sitemap/__tests__/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-sitemap/__tests__/index'>;
}
declare module 'gatsby-plugin-sitemap/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-sitemap/gatsby-node'>;
}
declare module 'gatsby-plugin-sitemap/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-sitemap/gatsby-ssr'>;
}
declare module 'gatsby-plugin-sitemap/index' {
  declare module.exports: $Exports<'gatsby-plugin-sitemap'>;
}
declare module 'gatsby-plugin-sitemap/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-sitemap'>;
}
declare module 'gatsby-plugin-sitemap/internals.js' {
  declare module.exports: $Exports<'gatsby-plugin-sitemap/internals'>;
}
