// flow-typed signature: 0acc52e331c5fddcf13bc8153c6e5d31
// flow-typed version: <<STUB>>/grid-styled_v^5.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grid-styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grid-styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grid-styled/dist/Box' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/div' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/Box' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/div' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/Flex' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/index' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/theme' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Flex' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/index' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/theme' {
  declare module.exports: any;
}

declare module 'grid-styled/emotion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grid-styled/dist/Box.js' {
  declare module.exports: $Exports<'grid-styled/dist/Box'>;
}
declare module 'grid-styled/dist/div.js' {
  declare module.exports: $Exports<'grid-styled/dist/div'>;
}
declare module 'grid-styled/dist/emotion/Box.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/Box'>;
}
declare module 'grid-styled/dist/emotion/div.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/div'>;
}
declare module 'grid-styled/dist/emotion/Flex.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/Flex'>;
}
declare module 'grid-styled/dist/emotion/index.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/index'>;
}
declare module 'grid-styled/dist/emotion/theme.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/theme'>;
}
declare module 'grid-styled/dist/Flex.js' {
  declare module.exports: $Exports<'grid-styled/dist/Flex'>;
}
declare module 'grid-styled/dist/index.js' {
  declare module.exports: $Exports<'grid-styled/dist/index'>;
}
declare module 'grid-styled/dist/theme.js' {
  declare module.exports: $Exports<'grid-styled/dist/theme'>;
}
declare module 'grid-styled/emotion.js' {
  declare module.exports: $Exports<'grid-styled/emotion'>;
}
