// flow-typed signature: 95b9bf39ca19501780cf4889b4f1f4c8
// flow-typed version: <<STUB>>/grid-styled_v^4.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grid-styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grid-styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grid-styled/dist/Box' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/div' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/Box' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/div' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/Flex' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/index' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/emotion/theme' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Flex' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Golden' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Grid' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Half' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/index' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/propTypes' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Quarter' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/remove-props' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/theme' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Third' {
  declare module.exports: any;
}

declare module 'grid-styled/emotion' {
  declare module.exports: any;
}

declare module 'grid-styled/tests/emotion' {
  declare module.exports: any;
}

declare module 'grid-styled/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grid-styled/dist/Box.js' {
  declare module.exports: $Exports<'grid-styled/dist/Box'>;
}
declare module 'grid-styled/dist/div.js' {
  declare module.exports: $Exports<'grid-styled/dist/div'>;
}
declare module 'grid-styled/dist/emotion/Box.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/Box'>;
}
declare module 'grid-styled/dist/emotion/div.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/div'>;
}
declare module 'grid-styled/dist/emotion/Flex.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/Flex'>;
}
declare module 'grid-styled/dist/emotion/index.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/index'>;
}
declare module 'grid-styled/dist/emotion/theme.js' {
  declare module.exports: $Exports<'grid-styled/dist/emotion/theme'>;
}
declare module 'grid-styled/dist/Flex.js' {
  declare module.exports: $Exports<'grid-styled/dist/Flex'>;
}
declare module 'grid-styled/dist/Golden.js' {
  declare module.exports: $Exports<'grid-styled/dist/Golden'>;
}
declare module 'grid-styled/dist/Grid.js' {
  declare module.exports: $Exports<'grid-styled/dist/Grid'>;
}
declare module 'grid-styled/dist/Half.js' {
  declare module.exports: $Exports<'grid-styled/dist/Half'>;
}
declare module 'grid-styled/dist/index.js' {
  declare module.exports: $Exports<'grid-styled/dist/index'>;
}
declare module 'grid-styled/dist/propTypes.js' {
  declare module.exports: $Exports<'grid-styled/dist/propTypes'>;
}
declare module 'grid-styled/dist/Quarter.js' {
  declare module.exports: $Exports<'grid-styled/dist/Quarter'>;
}
declare module 'grid-styled/dist/remove-props.js' {
  declare module.exports: $Exports<'grid-styled/dist/remove-props'>;
}
declare module 'grid-styled/dist/theme.js' {
  declare module.exports: $Exports<'grid-styled/dist/theme'>;
}
declare module 'grid-styled/dist/Third.js' {
  declare module.exports: $Exports<'grid-styled/dist/Third'>;
}
declare module 'grid-styled/emotion.js' {
  declare module.exports: $Exports<'grid-styled/emotion'>;
}
declare module 'grid-styled/tests/emotion.js' {
  declare module.exports: $Exports<'grid-styled/tests/emotion'>;
}
declare module 'grid-styled/tests/index.js' {
  declare module.exports: $Exports<'grid-styled/tests/index'>;
}
