// flow-typed signature: 31dbfb869f24fa3963a800ff94861653
// flow-typed version: <<STUB>>/netlify-cms_v^2.0.6/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify-cms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify-cms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify-cms/dist/cms' {
  declare module.exports: any;
}

declare module 'netlify-cms/dist/netlify-cms' {
  declare module.exports: any;
}

declare module 'netlify-cms/scripts/deprecate-old-dist' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/editor-components' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/widgets' {
  declare module.exports: any;
}

declare module 'netlify-cms/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify-cms/dist/cms.js' {
  declare module.exports: $Exports<'netlify-cms/dist/cms'>;
}
declare module 'netlify-cms/dist/netlify-cms.js' {
  declare module.exports: $Exports<'netlify-cms/dist/netlify-cms'>;
}
declare module 'netlify-cms/scripts/deprecate-old-dist.js' {
  declare module.exports: $Exports<'netlify-cms/scripts/deprecate-old-dist'>;
}
declare module 'netlify-cms/src/backends.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends'>;
}
declare module 'netlify-cms/src/editor-components.js' {
  declare module.exports: $Exports<'netlify-cms/src/editor-components'>;
}
declare module 'netlify-cms/src/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/index'>;
}
declare module 'netlify-cms/src/widgets.js' {
  declare module.exports: $Exports<'netlify-cms/src/widgets'>;
}
declare module 'netlify-cms/webpack.config.js' {
  declare module.exports: $Exports<'netlify-cms/webpack.config'>;
}
