// flow-typed signature: 7a3c375ba0e49f38077927d8b56bfd06
// flow-typed version: <<STUB>>/netlify-cms_v^1.9.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify-cms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify-cms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify-cms/dist/cms' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/__tests__/config.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/auth' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/collections' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/config' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/editorialWorkflow' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/entries' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/media' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/mediaLibrary' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/actions/search' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/backend' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/git-gateway/API' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/git-gateway/AuthenticationPage' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/git-gateway/GitHubAPI' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/git-gateway/GitLabAPI' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/git-gateway/implementation' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/github/__tests__/API.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/github/API' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/github/AuthenticationPage' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/github/implementation' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/gitlab/API' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/gitlab/AuthenticationPage' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/gitlab/implementation' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/test-repo/AuthenticationPage' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/backends/test-repo/implementation' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/bootstrap' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/App/App' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/App/Header' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/App/NotFoundPage' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Collection' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/CollectionTop' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Entries/Entries' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Entries/EntriesCollection' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Entries/EntriesSearch' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Entries/EntryCard' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Entries/EntryListing' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Collection/Sidebar' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/Editor' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorControlPane/EditorControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorControlPane/EditorControlPane' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorControlPane/Widget' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorInterface' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreviewContent' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreviewPane' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/PreviewHOC' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorScrollSync/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorScrollSync/ScrollSync' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorScrollSync/ScrollSyncPane' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorToggle' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/EditorToolbar' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Editor/withWorkflow' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Boolean/BooleanControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Date/DateControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Date/DatePreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/DateTime/DateTimeControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/DateTime/DateTimePreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/File/FileControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/File/FilePreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Image/ImageControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Image/ImagePreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/List/ListControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/List/ListPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/plugins' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/RawEditor/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/Toolbar' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/ToolbarButton' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/keys' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/plugins' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/renderers' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/Shortcode' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/validators' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownPreview/__tests__/renderer.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownPreview/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkAllowHtmlEntities.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkAssertParents.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkEscapeMarkdownEntities.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkPaddedLinks.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkStripTrailingBreaks.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/slate.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/rehypePaperEmoji' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkAllowHtmlEntities' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkAssertParents' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkEscapeMarkdownEntities' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkImagesToText' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkPaddedLinks' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkRehypeShortcodes' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkShortcodes' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkSlate' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkSquashReferences' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkStripTrailingBreaks' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkWrapHtml' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/slateRemark' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Number/NumberControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Number/NumberPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Object/ObjectControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Object/ObjectPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Relation/RelationControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Relation/RelationPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Select/SelectControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Select/SelectPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/String/StringControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/String/StringPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Text/TextControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Text/TextPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Unknown/UnknownControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/Unknown/UnknownPreview' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/EditorWidgets/withMedia/withMediaControl' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/MarkdownPlugins/image' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/MarkdownPlugins/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/MediaLibrary/MediaLibrary' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/DragDrop/DragDrop' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Dropdown/Dropdown' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/ErrorBoundary/ErrorBoundary' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/FileUploadButton/FileUploadButton' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Icon/Icon' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Icon/icons' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Icon/images/_index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/ListItemTopBar/ListItemTopBar' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Loader/Loader' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Modal/Modal' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Toast/Toast' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/UI/Toggle/Toggle' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Workflow/Workflow' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Workflow/WorkflowCard' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/components/Workflow/WorkflowList' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/constants/collectionTypes' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/constants/collectionViews' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/constants/fieldInference' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/constants/publishModes' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/constants/validationErrorTypes' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/__tests__/frontmatter.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/formats' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/frontmatter' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/helpers' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/json' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/toml' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/formats/yaml' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/integrations/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/integrations/providers/algolia/implementation' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/integrations/providers/assetStore/implementation' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/__tests__/pathHelper.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/__tests__/urlHelper.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/consoleError' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/implicit-oauth' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/LocalForage' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/netlify-auth' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/pathHelper' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/promiseHelper' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/randomGenerator' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/regexHelper' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/registry' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/serializeEntryValues' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/textHelper' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/unsentRequest' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/lib/urlHelper' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/__tests__/auth.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/__tests__/collections.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/__tests__/config.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/__tests__/entries.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/__tests__/entryDraft.spec' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/auth' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/collections' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/combinedReducer' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/config' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/cursors' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/editorialWorkflow' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/entries' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/entryDraft' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/globalUI' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/index' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/integrations' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/mediaLibrary' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/medias' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/reducers/search' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/redux/configureStore' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/redux/middleware/waitUntilAction' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/routing/history' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/valueObjects/AssetProxy' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/valueObjects/Cursor' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/valueObjects/Entry' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/valueObjects/errors/APIError' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/valueObjects/errors/EditorialWorkflowError' {
  declare module.exports: any;
}

declare module 'netlify-cms/src/valueObjects/errors/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify-cms/dist/cms.js' {
  declare module.exports: $Exports<'netlify-cms/dist/cms'>;
}
declare module 'netlify-cms/src/actions/__tests__/config.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/__tests__/config.spec'>;
}
declare module 'netlify-cms/src/actions/auth.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/auth'>;
}
declare module 'netlify-cms/src/actions/collections.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/collections'>;
}
declare module 'netlify-cms/src/actions/config.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/config'>;
}
declare module 'netlify-cms/src/actions/editorialWorkflow.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/editorialWorkflow'>;
}
declare module 'netlify-cms/src/actions/entries.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/entries'>;
}
declare module 'netlify-cms/src/actions/media.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/media'>;
}
declare module 'netlify-cms/src/actions/mediaLibrary.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/mediaLibrary'>;
}
declare module 'netlify-cms/src/actions/search.js' {
  declare module.exports: $Exports<'netlify-cms/src/actions/search'>;
}
declare module 'netlify-cms/src/backends/backend.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/backend'>;
}
declare module 'netlify-cms/src/backends/git-gateway/API.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/git-gateway/API'>;
}
declare module 'netlify-cms/src/backends/git-gateway/AuthenticationPage.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/git-gateway/AuthenticationPage'>;
}
declare module 'netlify-cms/src/backends/git-gateway/GitHubAPI.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/git-gateway/GitHubAPI'>;
}
declare module 'netlify-cms/src/backends/git-gateway/GitLabAPI.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/git-gateway/GitLabAPI'>;
}
declare module 'netlify-cms/src/backends/git-gateway/implementation.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/git-gateway/implementation'>;
}
declare module 'netlify-cms/src/backends/github/__tests__/API.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/github/__tests__/API.spec'>;
}
declare module 'netlify-cms/src/backends/github/API.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/github/API'>;
}
declare module 'netlify-cms/src/backends/github/AuthenticationPage.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/github/AuthenticationPage'>;
}
declare module 'netlify-cms/src/backends/github/implementation.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/github/implementation'>;
}
declare module 'netlify-cms/src/backends/gitlab/API.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/gitlab/API'>;
}
declare module 'netlify-cms/src/backends/gitlab/AuthenticationPage.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/gitlab/AuthenticationPage'>;
}
declare module 'netlify-cms/src/backends/gitlab/implementation.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/gitlab/implementation'>;
}
declare module 'netlify-cms/src/backends/test-repo/AuthenticationPage.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/test-repo/AuthenticationPage'>;
}
declare module 'netlify-cms/src/backends/test-repo/implementation.js' {
  declare module.exports: $Exports<'netlify-cms/src/backends/test-repo/implementation'>;
}
declare module 'netlify-cms/src/bootstrap.js' {
  declare module.exports: $Exports<'netlify-cms/src/bootstrap'>;
}
declare module 'netlify-cms/src/components/App/App.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/App/App'>;
}
declare module 'netlify-cms/src/components/App/Header.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/App/Header'>;
}
declare module 'netlify-cms/src/components/App/NotFoundPage.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/App/NotFoundPage'>;
}
declare module 'netlify-cms/src/components/Collection/Collection.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Collection'>;
}
declare module 'netlify-cms/src/components/Collection/CollectionTop.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/CollectionTop'>;
}
declare module 'netlify-cms/src/components/Collection/Entries/Entries.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Entries/Entries'>;
}
declare module 'netlify-cms/src/components/Collection/Entries/EntriesCollection.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Entries/EntriesCollection'>;
}
declare module 'netlify-cms/src/components/Collection/Entries/EntriesSearch.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Entries/EntriesSearch'>;
}
declare module 'netlify-cms/src/components/Collection/Entries/EntryCard.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Entries/EntryCard'>;
}
declare module 'netlify-cms/src/components/Collection/Entries/EntryListing.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Entries/EntryListing'>;
}
declare module 'netlify-cms/src/components/Collection/Sidebar.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Collection/Sidebar'>;
}
declare module 'netlify-cms/src/components/Editor/Editor.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/Editor'>;
}
declare module 'netlify-cms/src/components/Editor/EditorControlPane/EditorControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorControlPane/EditorControl'>;
}
declare module 'netlify-cms/src/components/Editor/EditorControlPane/EditorControlPane.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorControlPane/EditorControlPane'>;
}
declare module 'netlify-cms/src/components/Editor/EditorControlPane/Widget.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorControlPane/Widget'>;
}
declare module 'netlify-cms/src/components/Editor/EditorInterface.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorInterface'>;
}
declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreview'>;
}
declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreviewContent.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreviewContent'>;
}
declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorPreviewPane/EditorPreviewPane'>;
}
declare module 'netlify-cms/src/components/Editor/EditorPreviewPane/PreviewHOC.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorPreviewPane/PreviewHOC'>;
}
declare module 'netlify-cms/src/components/Editor/EditorScrollSync/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorScrollSync/index'>;
}
declare module 'netlify-cms/src/components/Editor/EditorScrollSync/ScrollSync.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorScrollSync/ScrollSync'>;
}
declare module 'netlify-cms/src/components/Editor/EditorScrollSync/ScrollSyncPane.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorScrollSync/ScrollSyncPane'>;
}
declare module 'netlify-cms/src/components/Editor/EditorToggle.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorToggle'>;
}
declare module 'netlify-cms/src/components/Editor/EditorToolbar.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/EditorToolbar'>;
}
declare module 'netlify-cms/src/components/Editor/withWorkflow.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Editor/withWorkflow'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Boolean/BooleanControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Boolean/BooleanControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Date/DateControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Date/DateControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Date/DatePreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Date/DatePreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/DateTime/DateTimeControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/DateTime/DateTimeControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/DateTime/DateTimePreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/DateTime/DateTimePreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/File/FileControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/File/FileControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/File/FilePreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/File/FilePreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Image/ImageControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Image/ImageControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Image/ImagePreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Image/ImagePreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/index'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/List/ListControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/List/ListControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/List/ListPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/List/ListPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/index'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/plugins.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/plugins'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/RawEditor/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/RawEditor/index'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/Toolbar.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/Toolbar'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/ToolbarButton.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/ToolbarButton'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/keys.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/keys'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/plugins.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/plugins'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/renderers.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/renderers'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/Shortcode.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/Shortcode'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/validators.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/validators'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownPreview/__tests__/renderer.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownPreview/__tests__/renderer.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownPreview/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/MarkdownPreview/index'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkAllowHtmlEntities.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkAllowHtmlEntities.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkAssertParents.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkAssertParents.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkEscapeMarkdownEntities.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkEscapeMarkdownEntities.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkPaddedLinks.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkPaddedLinks.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkStripTrailingBreaks.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/remarkStripTrailingBreaks.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/slate.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/__tests__/slate.spec'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/index'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/rehypePaperEmoji.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/rehypePaperEmoji'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkAllowHtmlEntities.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkAllowHtmlEntities'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkAssertParents.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkAssertParents'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkEscapeMarkdownEntities.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkEscapeMarkdownEntities'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkImagesToText.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkImagesToText'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkPaddedLinks.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkPaddedLinks'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkRehypeShortcodes.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkRehypeShortcodes'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkShortcodes.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkShortcodes'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkSlate.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkSlate'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkSquashReferences.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkSquashReferences'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkStripTrailingBreaks.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkStripTrailingBreaks'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkWrapHtml.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/remarkWrapHtml'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Markdown/serializers/slateRemark.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Markdown/serializers/slateRemark'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Number/NumberControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Number/NumberControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Number/NumberPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Number/NumberPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Object/ObjectControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Object/ObjectControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Object/ObjectPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Object/ObjectPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Relation/RelationControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Relation/RelationControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Relation/RelationPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Relation/RelationPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Select/SelectControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Select/SelectControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Select/SelectPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Select/SelectPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/String/StringControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/String/StringControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/String/StringPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/String/StringPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Text/TextControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Text/TextControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Text/TextPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Text/TextPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Unknown/UnknownControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Unknown/UnknownControl'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/Unknown/UnknownPreview.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/Unknown/UnknownPreview'>;
}
declare module 'netlify-cms/src/components/EditorWidgets/withMedia/withMediaControl.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/EditorWidgets/withMedia/withMediaControl'>;
}
declare module 'netlify-cms/src/components/MarkdownPlugins/image.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/MarkdownPlugins/image'>;
}
declare module 'netlify-cms/src/components/MarkdownPlugins/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/MarkdownPlugins/index'>;
}
declare module 'netlify-cms/src/components/MediaLibrary/MediaLibrary.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/MediaLibrary/MediaLibrary'>;
}
declare module 'netlify-cms/src/components/UI/DragDrop/DragDrop.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/DragDrop/DragDrop'>;
}
declare module 'netlify-cms/src/components/UI/Dropdown/Dropdown.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Dropdown/Dropdown'>;
}
declare module 'netlify-cms/src/components/UI/ErrorBoundary/ErrorBoundary.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/ErrorBoundary/ErrorBoundary'>;
}
declare module 'netlify-cms/src/components/UI/FileUploadButton/FileUploadButton.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/FileUploadButton/FileUploadButton'>;
}
declare module 'netlify-cms/src/components/UI/Icon/Icon.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Icon/Icon'>;
}
declare module 'netlify-cms/src/components/UI/Icon/icons.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Icon/icons'>;
}
declare module 'netlify-cms/src/components/UI/Icon/images/_index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Icon/images/_index'>;
}
declare module 'netlify-cms/src/components/UI/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/index'>;
}
declare module 'netlify-cms/src/components/UI/ListItemTopBar/ListItemTopBar.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/ListItemTopBar/ListItemTopBar'>;
}
declare module 'netlify-cms/src/components/UI/Loader/Loader.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Loader/Loader'>;
}
declare module 'netlify-cms/src/components/UI/Modal/Modal.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Modal/Modal'>;
}
declare module 'netlify-cms/src/components/UI/Toast/Toast.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Toast/Toast'>;
}
declare module 'netlify-cms/src/components/UI/Toggle/Toggle.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/UI/Toggle/Toggle'>;
}
declare module 'netlify-cms/src/components/Workflow/Workflow.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Workflow/Workflow'>;
}
declare module 'netlify-cms/src/components/Workflow/WorkflowCard.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Workflow/WorkflowCard'>;
}
declare module 'netlify-cms/src/components/Workflow/WorkflowList.js' {
  declare module.exports: $Exports<'netlify-cms/src/components/Workflow/WorkflowList'>;
}
declare module 'netlify-cms/src/constants/collectionTypes.js' {
  declare module.exports: $Exports<'netlify-cms/src/constants/collectionTypes'>;
}
declare module 'netlify-cms/src/constants/collectionViews.js' {
  declare module.exports: $Exports<'netlify-cms/src/constants/collectionViews'>;
}
declare module 'netlify-cms/src/constants/fieldInference.js' {
  declare module.exports: $Exports<'netlify-cms/src/constants/fieldInference'>;
}
declare module 'netlify-cms/src/constants/publishModes.js' {
  declare module.exports: $Exports<'netlify-cms/src/constants/publishModes'>;
}
declare module 'netlify-cms/src/constants/validationErrorTypes.js' {
  declare module.exports: $Exports<'netlify-cms/src/constants/validationErrorTypes'>;
}
declare module 'netlify-cms/src/formats/__tests__/frontmatter.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/__tests__/frontmatter.spec'>;
}
declare module 'netlify-cms/src/formats/formats.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/formats'>;
}
declare module 'netlify-cms/src/formats/frontmatter.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/frontmatter'>;
}
declare module 'netlify-cms/src/formats/helpers.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/helpers'>;
}
declare module 'netlify-cms/src/formats/json.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/json'>;
}
declare module 'netlify-cms/src/formats/toml.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/toml'>;
}
declare module 'netlify-cms/src/formats/yaml.js' {
  declare module.exports: $Exports<'netlify-cms/src/formats/yaml'>;
}
declare module 'netlify-cms/src/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/index'>;
}
declare module 'netlify-cms/src/integrations/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/integrations/index'>;
}
declare module 'netlify-cms/src/integrations/providers/algolia/implementation.js' {
  declare module.exports: $Exports<'netlify-cms/src/integrations/providers/algolia/implementation'>;
}
declare module 'netlify-cms/src/integrations/providers/assetStore/implementation.js' {
  declare module.exports: $Exports<'netlify-cms/src/integrations/providers/assetStore/implementation'>;
}
declare module 'netlify-cms/src/lib/__tests__/pathHelper.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/__tests__/pathHelper.spec'>;
}
declare module 'netlify-cms/src/lib/__tests__/urlHelper.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/__tests__/urlHelper.spec'>;
}
declare module 'netlify-cms/src/lib/consoleError.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/consoleError'>;
}
declare module 'netlify-cms/src/lib/implicit-oauth.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/implicit-oauth'>;
}
declare module 'netlify-cms/src/lib/LocalForage.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/LocalForage'>;
}
declare module 'netlify-cms/src/lib/netlify-auth.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/netlify-auth'>;
}
declare module 'netlify-cms/src/lib/pathHelper.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/pathHelper'>;
}
declare module 'netlify-cms/src/lib/promiseHelper.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/promiseHelper'>;
}
declare module 'netlify-cms/src/lib/randomGenerator.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/randomGenerator'>;
}
declare module 'netlify-cms/src/lib/regexHelper.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/regexHelper'>;
}
declare module 'netlify-cms/src/lib/registry.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/registry'>;
}
declare module 'netlify-cms/src/lib/serializeEntryValues.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/serializeEntryValues'>;
}
declare module 'netlify-cms/src/lib/textHelper.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/textHelper'>;
}
declare module 'netlify-cms/src/lib/unsentRequest.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/unsentRequest'>;
}
declare module 'netlify-cms/src/lib/urlHelper.js' {
  declare module.exports: $Exports<'netlify-cms/src/lib/urlHelper'>;
}
declare module 'netlify-cms/src/reducers/__tests__/auth.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/__tests__/auth.spec'>;
}
declare module 'netlify-cms/src/reducers/__tests__/collections.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/__tests__/collections.spec'>;
}
declare module 'netlify-cms/src/reducers/__tests__/config.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/__tests__/config.spec'>;
}
declare module 'netlify-cms/src/reducers/__tests__/entries.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/__tests__/entries.spec'>;
}
declare module 'netlify-cms/src/reducers/__tests__/entryDraft.spec.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/__tests__/entryDraft.spec'>;
}
declare module 'netlify-cms/src/reducers/auth.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/auth'>;
}
declare module 'netlify-cms/src/reducers/collections.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/collections'>;
}
declare module 'netlify-cms/src/reducers/combinedReducer.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/combinedReducer'>;
}
declare module 'netlify-cms/src/reducers/config.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/config'>;
}
declare module 'netlify-cms/src/reducers/cursors.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/cursors'>;
}
declare module 'netlify-cms/src/reducers/editorialWorkflow.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/editorialWorkflow'>;
}
declare module 'netlify-cms/src/reducers/entries.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/entries'>;
}
declare module 'netlify-cms/src/reducers/entryDraft.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/entryDraft'>;
}
declare module 'netlify-cms/src/reducers/globalUI.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/globalUI'>;
}
declare module 'netlify-cms/src/reducers/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/index'>;
}
declare module 'netlify-cms/src/reducers/integrations.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/integrations'>;
}
declare module 'netlify-cms/src/reducers/mediaLibrary.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/mediaLibrary'>;
}
declare module 'netlify-cms/src/reducers/medias.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/medias'>;
}
declare module 'netlify-cms/src/reducers/search.js' {
  declare module.exports: $Exports<'netlify-cms/src/reducers/search'>;
}
declare module 'netlify-cms/src/redux/configureStore.js' {
  declare module.exports: $Exports<'netlify-cms/src/redux/configureStore'>;
}
declare module 'netlify-cms/src/redux/middleware/waitUntilAction.js' {
  declare module.exports: $Exports<'netlify-cms/src/redux/middleware/waitUntilAction'>;
}
declare module 'netlify-cms/src/routing/history.js' {
  declare module.exports: $Exports<'netlify-cms/src/routing/history'>;
}
declare module 'netlify-cms/src/valueObjects/AssetProxy.js' {
  declare module.exports: $Exports<'netlify-cms/src/valueObjects/AssetProxy'>;
}
declare module 'netlify-cms/src/valueObjects/Cursor.js' {
  declare module.exports: $Exports<'netlify-cms/src/valueObjects/Cursor'>;
}
declare module 'netlify-cms/src/valueObjects/Entry.js' {
  declare module.exports: $Exports<'netlify-cms/src/valueObjects/Entry'>;
}
declare module 'netlify-cms/src/valueObjects/errors/APIError.js' {
  declare module.exports: $Exports<'netlify-cms/src/valueObjects/errors/APIError'>;
}
declare module 'netlify-cms/src/valueObjects/errors/EditorialWorkflowError.js' {
  declare module.exports: $Exports<'netlify-cms/src/valueObjects/errors/EditorialWorkflowError'>;
}
declare module 'netlify-cms/src/valueObjects/errors/index.js' {
  declare module.exports: $Exports<'netlify-cms/src/valueObjects/errors/index'>;
}
