// flow-typed signature: 819dfe2a29cbba552422bef2f4e1ce14
// flow-typed version: <<STUB>>/react-vk_v^2.0.6/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-vk/build/AllowMessagesFromCommunity' {
  declare module.exports: any;
}

declare module 'react-vk/build/API' {
  declare module.exports: any;
}

declare module 'react-vk/build/App' {
  declare module.exports: any;
}

declare module 'react-vk/build/Auth' {
  declare module.exports: any;
}

declare module 'react-vk/build/Comments' {
  declare module.exports: any;
}

declare module 'react-vk/build/CommentsBrowse' {
  declare module.exports: any;
}

declare module 'react-vk/build/CommunityMessages' {
  declare module.exports: any;
}

declare module 'react-vk/build/ContactUs' {
  declare module.exports: any;
}

declare module 'react-vk/build/Group' {
  declare module.exports: any;
}

declare module 'react-vk/build/index' {
  declare module.exports: any;
}

declare module 'react-vk/build/Like' {
  declare module.exports: any;
}

declare module 'react-vk/build/Playlist' {
  declare module.exports: any;
}

declare module 'react-vk/build/Poll' {
  declare module.exports: any;
}

declare module 'react-vk/build/Post' {
  declare module.exports: any;
}

declare module 'react-vk/build/Recommended' {
  declare module.exports: any;
}

declare module 'react-vk/build/Subscribe' {
  declare module.exports: any;
}

declare module 'react-vk/build/VK' {
  declare module.exports: any;
}

declare module 'react-vk/build/VKContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-vk/build/AllowMessagesFromCommunity.js' {
  declare module.exports: $Exports<'react-vk/build/AllowMessagesFromCommunity'>;
}
declare module 'react-vk/build/API.js' {
  declare module.exports: $Exports<'react-vk/build/API'>;
}
declare module 'react-vk/build/App.js' {
  declare module.exports: $Exports<'react-vk/build/App'>;
}
declare module 'react-vk/build/Auth.js' {
  declare module.exports: $Exports<'react-vk/build/Auth'>;
}
declare module 'react-vk/build/Comments.js' {
  declare module.exports: $Exports<'react-vk/build/Comments'>;
}
declare module 'react-vk/build/CommentsBrowse.js' {
  declare module.exports: $Exports<'react-vk/build/CommentsBrowse'>;
}
declare module 'react-vk/build/CommunityMessages.js' {
  declare module.exports: $Exports<'react-vk/build/CommunityMessages'>;
}
declare module 'react-vk/build/ContactUs.js' {
  declare module.exports: $Exports<'react-vk/build/ContactUs'>;
}
declare module 'react-vk/build/Group.js' {
  declare module.exports: $Exports<'react-vk/build/Group'>;
}
declare module 'react-vk/build/index.js' {
  declare module.exports: $Exports<'react-vk/build/index'>;
}
declare module 'react-vk/build/Like.js' {
  declare module.exports: $Exports<'react-vk/build/Like'>;
}
declare module 'react-vk/build/Playlist.js' {
  declare module.exports: $Exports<'react-vk/build/Playlist'>;
}
declare module 'react-vk/build/Poll.js' {
  declare module.exports: $Exports<'react-vk/build/Poll'>;
}
declare module 'react-vk/build/Post.js' {
  declare module.exports: $Exports<'react-vk/build/Post'>;
}
declare module 'react-vk/build/Recommended.js' {
  declare module.exports: $Exports<'react-vk/build/Recommended'>;
}
declare module 'react-vk/build/Subscribe.js' {
  declare module.exports: $Exports<'react-vk/build/Subscribe'>;
}
declare module 'react-vk/build/VK.js' {
  declare module.exports: $Exports<'react-vk/build/VK'>;
}
declare module 'react-vk/build/VKContext.js' {
  declare module.exports: $Exports<'react-vk/build/VKContext'>;
}
