// flow-typed signature: 9c69d4d944823867edd3757445fc2e6e
// flow-typed version: <<STUB>>/react-lazyload_v^2.3.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lazyload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lazyload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lazyload/lib/decorator' {
  declare module.exports: any;
}

declare module 'react-lazyload/lib/index' {
  declare module.exports: any;
}

declare module 'react-lazyload/lib/utils/debounce' {
  declare module.exports: any;
}

declare module 'react-lazyload/lib/utils/event' {
  declare module.exports: any;
}

declare module 'react-lazyload/lib/utils/scrollParent' {
  declare module.exports: any;
}

declare module 'react-lazyload/lib/utils/throttle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lazyload/lib/decorator.js' {
  declare module.exports: $Exports<'react-lazyload/lib/decorator'>;
}
declare module 'react-lazyload/lib/index.js' {
  declare module.exports: $Exports<'react-lazyload/lib/index'>;
}
declare module 'react-lazyload/lib/utils/debounce.js' {
  declare module.exports: $Exports<'react-lazyload/lib/utils/debounce'>;
}
declare module 'react-lazyload/lib/utils/event.js' {
  declare module.exports: $Exports<'react-lazyload/lib/utils/event'>;
}
declare module 'react-lazyload/lib/utils/scrollParent.js' {
  declare module.exports: $Exports<'react-lazyload/lib/utils/scrollParent'>;
}
declare module 'react-lazyload/lib/utils/throttle.js' {
  declare module.exports: $Exports<'react-lazyload/lib/utils/throttle'>;
}
