// flow-typed signature: 133c6d5d32b06389cf0d638d510ec984
// flow-typed version: <<STUB>>/react-yandex-metrika_v^2.3.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-yandex-metrika'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-yandex-metrika' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-yandex-metrika/lib/component' {
  declare module.exports: any;
}

declare module 'react-yandex-metrika/lib/constants' {
  declare module.exports: any;
}

declare module 'react-yandex-metrika/lib/index' {
  declare module.exports: any;
}

declare module 'react-yandex-metrika/lib/init' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-yandex-metrika/lib/component.js' {
  declare module.exports: $Exports<'react-yandex-metrika/lib/component'>;
}
declare module 'react-yandex-metrika/lib/constants.js' {
  declare module.exports: $Exports<'react-yandex-metrika/lib/constants'>;
}
declare module 'react-yandex-metrika/lib/index.js' {
  declare module.exports: $Exports<'react-yandex-metrika/lib/index'>;
}
declare module 'react-yandex-metrika/lib/init.js' {
  declare module.exports: $Exports<'react-yandex-metrika/lib/init'>;
}
