// flow-typed signature: 4a6d70585a6a11d3af47d73ddf7384fb
// flow-typed version: <<STUB>>/react-facebook_v^5.0.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook/dist/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/EmbeddedVideo' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/index' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Send' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/dist/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook/jest/setup' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/EmbeddedVideo' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/index' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Send' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/module/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook/module/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook/module/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook/module/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/module/EmbeddedVideo' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/module/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/module/index' {
  declare module.exports: any;
}

declare module 'react-facebook/module/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/module/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/module/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook/module/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Send' {
  declare module.exports: any;
}

declare module 'react-facebook/module/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/module/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook/module/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/module/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/module/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook/setupJest' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/src/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/MessengerColor' {
  declare module.exports: any;
}

declare module 'react-facebook/src/constants/MessengerSize' {
  declare module.exports: any;
}

declare module 'react-facebook/src/CustomChat' {
  declare module.exports: any;
}

declare module 'react-facebook/src/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/src/EmbeddedVideo' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/src/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/src/index' {
  declare module.exports: any;
}

declare module 'react-facebook/src/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/src/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/src/MessageUs' {
  declare module.exports: any;
}

declare module 'react-facebook/src/MessengerCheckbox' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Send' {
  declare module.exports: any;
}

declare module 'react-facebook/src/SendToMessenger' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/src/Share.test' {
  declare module.exports: any;
}

declare module 'react-facebook/src/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/src/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/src/utils/getCurrentHref' {
  declare module.exports: any;
}

declare module 'react-facebook/tempPolyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook/dist/Comments.js' {
  declare module.exports: $Exports<'react-facebook/dist/Comments'>;
}
declare module 'react-facebook/dist/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook/dist/CommentsCount'>;
}
declare module 'react-facebook/dist/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/ColorScheme'>;
}
declare module 'react-facebook/dist/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/dist/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/LikeAction'>;
}
declare module 'react-facebook/dist/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/LikeLayout'>;
}
declare module 'react-facebook/dist/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/LikeSize'>;
}
declare module 'react-facebook/dist/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/MessengerColor'>;
}
declare module 'react-facebook/dist/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook/dist/constants/MessengerSize'>;
}
declare module 'react-facebook/dist/CustomChat.js' {
  declare module.exports: $Exports<'react-facebook/dist/CustomChat'>;
}
declare module 'react-facebook/dist/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook/dist/EmbeddedPost'>;
}
declare module 'react-facebook/dist/EmbeddedVideo.js' {
  declare module.exports: $Exports<'react-facebook/dist/EmbeddedVideo'>;
}
declare module 'react-facebook/dist/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/dist/Facebook'>;
}
declare module 'react-facebook/dist/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook/dist/FacebookProvider'>;
}
declare module 'react-facebook/dist/Feed.js' {
  declare module.exports: $Exports<'react-facebook/dist/Feed'>;
}
declare module 'react-facebook/dist/index.js' {
  declare module.exports: $Exports<'react-facebook/dist/index'>;
}
declare module 'react-facebook/dist/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook/dist/InitFacebook'>;
}
declare module 'react-facebook/dist/Like.js' {
  declare module.exports: $Exports<'react-facebook/dist/Like'>;
}
declare module 'react-facebook/dist/Login.js' {
  declare module.exports: $Exports<'react-facebook/dist/Login'>;
}
declare module 'react-facebook/dist/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook/dist/LoginButton'>;
}
declare module 'react-facebook/dist/MessageUs.js' {
  declare module.exports: $Exports<'react-facebook/dist/MessageUs'>;
}
declare module 'react-facebook/dist/MessengerCheckbox.js' {
  declare module.exports: $Exports<'react-facebook/dist/MessengerCheckbox'>;
}
declare module 'react-facebook/dist/Page.js' {
  declare module.exports: $Exports<'react-facebook/dist/Page'>;
}
declare module 'react-facebook/dist/Parser.js' {
  declare module.exports: $Exports<'react-facebook/dist/Parser'>;
}
declare module 'react-facebook/dist/Process.js' {
  declare module.exports: $Exports<'react-facebook/dist/Process'>;
}
declare module 'react-facebook/dist/Send.js' {
  declare module.exports: $Exports<'react-facebook/dist/Send'>;
}
declare module 'react-facebook/dist/SendToMessenger.js' {
  declare module.exports: $Exports<'react-facebook/dist/SendToMessenger'>;
}
declare module 'react-facebook/dist/Share.js' {
  declare module.exports: $Exports<'react-facebook/dist/Share'>;
}
declare module 'react-facebook/dist/Share.test.js' {
  declare module.exports: $Exports<'react-facebook/dist/Share.test'>;
}
declare module 'react-facebook/dist/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook/dist/ShareButton'>;
}
declare module 'react-facebook/dist/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/dist/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/dist/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/dist/utils/getCurrentHref'>;
}
declare module 'react-facebook/jest/setup.js' {
  declare module.exports: $Exports<'react-facebook/jest/setup'>;
}
declare module 'react-facebook/lib/Comments.js' {
  declare module.exports: $Exports<'react-facebook/lib/Comments'>;
}
declare module 'react-facebook/lib/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook/lib/CommentsCount'>;
}
declare module 'react-facebook/lib/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/ColorScheme'>;
}
declare module 'react-facebook/lib/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/lib/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeAction'>;
}
declare module 'react-facebook/lib/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeLayout'>;
}
declare module 'react-facebook/lib/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeSize'>;
}
declare module 'react-facebook/lib/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/MessengerColor'>;
}
declare module 'react-facebook/lib/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/MessengerSize'>;
}
declare module 'react-facebook/lib/CustomChat.js' {
  declare module.exports: $Exports<'react-facebook/lib/CustomChat'>;
}
declare module 'react-facebook/lib/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook/lib/EmbeddedPost'>;
}
declare module 'react-facebook/lib/EmbeddedVideo.js' {
  declare module.exports: $Exports<'react-facebook/lib/EmbeddedVideo'>;
}
declare module 'react-facebook/lib/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/lib/Facebook'>;
}
declare module 'react-facebook/lib/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook/lib/FacebookProvider'>;
}
declare module 'react-facebook/lib/Feed.js' {
  declare module.exports: $Exports<'react-facebook/lib/Feed'>;
}
declare module 'react-facebook/lib/index.js' {
  declare module.exports: $Exports<'react-facebook/lib/index'>;
}
declare module 'react-facebook/lib/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook/lib/InitFacebook'>;
}
declare module 'react-facebook/lib/Like.js' {
  declare module.exports: $Exports<'react-facebook/lib/Like'>;
}
declare module 'react-facebook/lib/Login.js' {
  declare module.exports: $Exports<'react-facebook/lib/Login'>;
}
declare module 'react-facebook/lib/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook/lib/LoginButton'>;
}
declare module 'react-facebook/lib/MessageUs.js' {
  declare module.exports: $Exports<'react-facebook/lib/MessageUs'>;
}
declare module 'react-facebook/lib/MessengerCheckbox.js' {
  declare module.exports: $Exports<'react-facebook/lib/MessengerCheckbox'>;
}
declare module 'react-facebook/lib/Page.js' {
  declare module.exports: $Exports<'react-facebook/lib/Page'>;
}
declare module 'react-facebook/lib/Parser.js' {
  declare module.exports: $Exports<'react-facebook/lib/Parser'>;
}
declare module 'react-facebook/lib/Process.js' {
  declare module.exports: $Exports<'react-facebook/lib/Process'>;
}
declare module 'react-facebook/lib/Send.js' {
  declare module.exports: $Exports<'react-facebook/lib/Send'>;
}
declare module 'react-facebook/lib/SendToMessenger.js' {
  declare module.exports: $Exports<'react-facebook/lib/SendToMessenger'>;
}
declare module 'react-facebook/lib/Share.js' {
  declare module.exports: $Exports<'react-facebook/lib/Share'>;
}
declare module 'react-facebook/lib/Share.test.js' {
  declare module.exports: $Exports<'react-facebook/lib/Share.test'>;
}
declare module 'react-facebook/lib/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook/lib/ShareButton'>;
}
declare module 'react-facebook/lib/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/lib/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/lib/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/lib/utils/getCurrentHref'>;
}
declare module 'react-facebook/module/Comments.js' {
  declare module.exports: $Exports<'react-facebook/module/Comments'>;
}
declare module 'react-facebook/module/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook/module/CommentsCount'>;
}
declare module 'react-facebook/module/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/ColorScheme'>;
}
declare module 'react-facebook/module/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/module/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/LikeAction'>;
}
declare module 'react-facebook/module/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/LikeLayout'>;
}
declare module 'react-facebook/module/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/LikeSize'>;
}
declare module 'react-facebook/module/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/MessengerColor'>;
}
declare module 'react-facebook/module/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook/module/constants/MessengerSize'>;
}
declare module 'react-facebook/module/CustomChat.js' {
  declare module.exports: $Exports<'react-facebook/module/CustomChat'>;
}
declare module 'react-facebook/module/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook/module/EmbeddedPost'>;
}
declare module 'react-facebook/module/EmbeddedVideo.js' {
  declare module.exports: $Exports<'react-facebook/module/EmbeddedVideo'>;
}
declare module 'react-facebook/module/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/module/Facebook'>;
}
declare module 'react-facebook/module/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook/module/FacebookProvider'>;
}
declare module 'react-facebook/module/Feed.js' {
  declare module.exports: $Exports<'react-facebook/module/Feed'>;
}
declare module 'react-facebook/module/index.js' {
  declare module.exports: $Exports<'react-facebook/module/index'>;
}
declare module 'react-facebook/module/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook/module/InitFacebook'>;
}
declare module 'react-facebook/module/Like.js' {
  declare module.exports: $Exports<'react-facebook/module/Like'>;
}
declare module 'react-facebook/module/Login.js' {
  declare module.exports: $Exports<'react-facebook/module/Login'>;
}
declare module 'react-facebook/module/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook/module/LoginButton'>;
}
declare module 'react-facebook/module/MessageUs.js' {
  declare module.exports: $Exports<'react-facebook/module/MessageUs'>;
}
declare module 'react-facebook/module/MessengerCheckbox.js' {
  declare module.exports: $Exports<'react-facebook/module/MessengerCheckbox'>;
}
declare module 'react-facebook/module/Page.js' {
  declare module.exports: $Exports<'react-facebook/module/Page'>;
}
declare module 'react-facebook/module/Parser.js' {
  declare module.exports: $Exports<'react-facebook/module/Parser'>;
}
declare module 'react-facebook/module/Process.js' {
  declare module.exports: $Exports<'react-facebook/module/Process'>;
}
declare module 'react-facebook/module/Send.js' {
  declare module.exports: $Exports<'react-facebook/module/Send'>;
}
declare module 'react-facebook/module/SendToMessenger.js' {
  declare module.exports: $Exports<'react-facebook/module/SendToMessenger'>;
}
declare module 'react-facebook/module/Share.js' {
  declare module.exports: $Exports<'react-facebook/module/Share'>;
}
declare module 'react-facebook/module/Share.test.js' {
  declare module.exports: $Exports<'react-facebook/module/Share.test'>;
}
declare module 'react-facebook/module/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook/module/ShareButton'>;
}
declare module 'react-facebook/module/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/module/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/module/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/module/utils/getCurrentHref'>;
}
declare module 'react-facebook/setupJest.js' {
  declare module.exports: $Exports<'react-facebook/setupJest'>;
}
declare module 'react-facebook/src/Comments.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Comments'>;
}
declare module 'react-facebook/src/CommentsCount.jsx' {
  declare module.exports: $Exports<'react-facebook/src/CommentsCount'>;
}
declare module 'react-facebook/src/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/ColorScheme'>;
}
declare module 'react-facebook/src/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/src/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/LikeAction'>;
}
declare module 'react-facebook/src/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/LikeLayout'>;
}
declare module 'react-facebook/src/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/LikeSize'>;
}
declare module 'react-facebook/src/constants/MessengerColor.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/MessengerColor'>;
}
declare module 'react-facebook/src/constants/MessengerSize.js' {
  declare module.exports: $Exports<'react-facebook/src/constants/MessengerSize'>;
}
declare module 'react-facebook/src/CustomChat.jsx' {
  declare module.exports: $Exports<'react-facebook/src/CustomChat'>;
}
declare module 'react-facebook/src/EmbeddedPost.jsx' {
  declare module.exports: $Exports<'react-facebook/src/EmbeddedPost'>;
}
declare module 'react-facebook/src/EmbeddedVideo.jsx' {
  declare module.exports: $Exports<'react-facebook/src/EmbeddedVideo'>;
}
declare module 'react-facebook/src/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/src/Facebook'>;
}
declare module 'react-facebook/src/FacebookProvider.jsx' {
  declare module.exports: $Exports<'react-facebook/src/FacebookProvider'>;
}
declare module 'react-facebook/src/Feed.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Feed'>;
}
declare module 'react-facebook/src/index.js' {
  declare module.exports: $Exports<'react-facebook/src/index'>;
}
declare module 'react-facebook/src/InitFacebook.jsx' {
  declare module.exports: $Exports<'react-facebook/src/InitFacebook'>;
}
declare module 'react-facebook/src/Like.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Like'>;
}
declare module 'react-facebook/src/Login.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Login'>;
}
declare module 'react-facebook/src/LoginButton.jsx' {
  declare module.exports: $Exports<'react-facebook/src/LoginButton'>;
}
declare module 'react-facebook/src/MessageUs.jsx' {
  declare module.exports: $Exports<'react-facebook/src/MessageUs'>;
}
declare module 'react-facebook/src/MessengerCheckbox.jsx' {
  declare module.exports: $Exports<'react-facebook/src/MessengerCheckbox'>;
}
declare module 'react-facebook/src/Page.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Page'>;
}
declare module 'react-facebook/src/Parser.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Parser'>;
}
declare module 'react-facebook/src/Process.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Process'>;
}
declare module 'react-facebook/src/Send.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Send'>;
}
declare module 'react-facebook/src/SendToMessenger.jsx' {
  declare module.exports: $Exports<'react-facebook/src/SendToMessenger'>;
}
declare module 'react-facebook/src/Share.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Share'>;
}
declare module 'react-facebook/src/Share.test.jsx' {
  declare module.exports: $Exports<'react-facebook/src/Share.test'>;
}
declare module 'react-facebook/src/ShareButton.jsx' {
  declare module.exports: $Exports<'react-facebook/src/ShareButton'>;
}
declare module 'react-facebook/src/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/src/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/src/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/src/utils/getCurrentHref'>;
}
declare module 'react-facebook/tempPolyfill.js' {
  declare module.exports: $Exports<'react-facebook/tempPolyfill'>;
}
