// flow-typed signature: bf90954bca0b7dc14f18e2daefdc0591
// flow-typed version: <<STUB>>/react-masonry-component_v^6.2.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-masonry-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-masonry-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-masonry-component/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-masonry-component/lib/index.js' {
  declare module.exports: $Exports<'react-masonry-component/lib/index'>;
}
