// flow-typed signature: e672e6dd75b9d3fb903513f94deb45c0
// flow-typed version: <<STUB>>/react-vk_v^3.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-vk/lib/AllowMessagesFromCommunity' {
  declare module.exports: any;
}

declare module 'react-vk/lib/API' {
  declare module.exports: any;
}

declare module 'react-vk/lib/App' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Article' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Auth' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Comments' {
  declare module.exports: any;
}

declare module 'react-vk/lib/CommentsBrowse' {
  declare module.exports: any;
}

declare module 'react-vk/lib/CommunityMessages' {
  declare module.exports: any;
}

declare module 'react-vk/lib/ContactUs' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Group' {
  declare module.exports: any;
}

declare module 'react-vk/lib/index' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Like' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Playlist' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Poll' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Post' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Recommended' {
  declare module.exports: any;
}

declare module 'react-vk/lib/Subscribe' {
  declare module.exports: any;
}

declare module 'react-vk/lib/VK' {
  declare module.exports: any;
}

declare module 'react-vk/lib/VKContext' {
  declare module.exports: any;
}

declare module 'react-vk/lib/vkPropTypes' {
  declare module.exports: any;
}

declare module 'react-vk/module/AllowMessagesFromCommunity' {
  declare module.exports: any;
}

declare module 'react-vk/module/API' {
  declare module.exports: any;
}

declare module 'react-vk/module/App' {
  declare module.exports: any;
}

declare module 'react-vk/module/Article' {
  declare module.exports: any;
}

declare module 'react-vk/module/Auth' {
  declare module.exports: any;
}

declare module 'react-vk/module/Comments' {
  declare module.exports: any;
}

declare module 'react-vk/module/CommentsBrowse' {
  declare module.exports: any;
}

declare module 'react-vk/module/CommunityMessages' {
  declare module.exports: any;
}

declare module 'react-vk/module/ContactUs' {
  declare module.exports: any;
}

declare module 'react-vk/module/Group' {
  declare module.exports: any;
}

declare module 'react-vk/module/index' {
  declare module.exports: any;
}

declare module 'react-vk/module/Like' {
  declare module.exports: any;
}

declare module 'react-vk/module/Playlist' {
  declare module.exports: any;
}

declare module 'react-vk/module/Poll' {
  declare module.exports: any;
}

declare module 'react-vk/module/Post' {
  declare module.exports: any;
}

declare module 'react-vk/module/Recommended' {
  declare module.exports: any;
}

declare module 'react-vk/module/Subscribe' {
  declare module.exports: any;
}

declare module 'react-vk/module/VK' {
  declare module.exports: any;
}

declare module 'react-vk/module/VKContext' {
  declare module.exports: any;
}

declare module 'react-vk/module/vkPropTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-vk/lib/AllowMessagesFromCommunity.js' {
  declare module.exports: $Exports<'react-vk/lib/AllowMessagesFromCommunity'>;
}
declare module 'react-vk/lib/API.js' {
  declare module.exports: $Exports<'react-vk/lib/API'>;
}
declare module 'react-vk/lib/App.js' {
  declare module.exports: $Exports<'react-vk/lib/App'>;
}
declare module 'react-vk/lib/Article.js' {
  declare module.exports: $Exports<'react-vk/lib/Article'>;
}
declare module 'react-vk/lib/Auth.js' {
  declare module.exports: $Exports<'react-vk/lib/Auth'>;
}
declare module 'react-vk/lib/Comments.js' {
  declare module.exports: $Exports<'react-vk/lib/Comments'>;
}
declare module 'react-vk/lib/CommentsBrowse.js' {
  declare module.exports: $Exports<'react-vk/lib/CommentsBrowse'>;
}
declare module 'react-vk/lib/CommunityMessages.js' {
  declare module.exports: $Exports<'react-vk/lib/CommunityMessages'>;
}
declare module 'react-vk/lib/ContactUs.js' {
  declare module.exports: $Exports<'react-vk/lib/ContactUs'>;
}
declare module 'react-vk/lib/Group.js' {
  declare module.exports: $Exports<'react-vk/lib/Group'>;
}
declare module 'react-vk/lib/index.js' {
  declare module.exports: $Exports<'react-vk/lib/index'>;
}
declare module 'react-vk/lib/Like.js' {
  declare module.exports: $Exports<'react-vk/lib/Like'>;
}
declare module 'react-vk/lib/Playlist.js' {
  declare module.exports: $Exports<'react-vk/lib/Playlist'>;
}
declare module 'react-vk/lib/Poll.js' {
  declare module.exports: $Exports<'react-vk/lib/Poll'>;
}
declare module 'react-vk/lib/Post.js' {
  declare module.exports: $Exports<'react-vk/lib/Post'>;
}
declare module 'react-vk/lib/Recommended.js' {
  declare module.exports: $Exports<'react-vk/lib/Recommended'>;
}
declare module 'react-vk/lib/Subscribe.js' {
  declare module.exports: $Exports<'react-vk/lib/Subscribe'>;
}
declare module 'react-vk/lib/VK.js' {
  declare module.exports: $Exports<'react-vk/lib/VK'>;
}
declare module 'react-vk/lib/VKContext.js' {
  declare module.exports: $Exports<'react-vk/lib/VKContext'>;
}
declare module 'react-vk/lib/vkPropTypes.js' {
  declare module.exports: $Exports<'react-vk/lib/vkPropTypes'>;
}
declare module 'react-vk/module/AllowMessagesFromCommunity.js' {
  declare module.exports: $Exports<'react-vk/module/AllowMessagesFromCommunity'>;
}
declare module 'react-vk/module/API.js' {
  declare module.exports: $Exports<'react-vk/module/API'>;
}
declare module 'react-vk/module/App.js' {
  declare module.exports: $Exports<'react-vk/module/App'>;
}
declare module 'react-vk/module/Article.js' {
  declare module.exports: $Exports<'react-vk/module/Article'>;
}
declare module 'react-vk/module/Auth.js' {
  declare module.exports: $Exports<'react-vk/module/Auth'>;
}
declare module 'react-vk/module/Comments.js' {
  declare module.exports: $Exports<'react-vk/module/Comments'>;
}
declare module 'react-vk/module/CommentsBrowse.js' {
  declare module.exports: $Exports<'react-vk/module/CommentsBrowse'>;
}
declare module 'react-vk/module/CommunityMessages.js' {
  declare module.exports: $Exports<'react-vk/module/CommunityMessages'>;
}
declare module 'react-vk/module/ContactUs.js' {
  declare module.exports: $Exports<'react-vk/module/ContactUs'>;
}
declare module 'react-vk/module/Group.js' {
  declare module.exports: $Exports<'react-vk/module/Group'>;
}
declare module 'react-vk/module/index.js' {
  declare module.exports: $Exports<'react-vk/module/index'>;
}
declare module 'react-vk/module/Like.js' {
  declare module.exports: $Exports<'react-vk/module/Like'>;
}
declare module 'react-vk/module/Playlist.js' {
  declare module.exports: $Exports<'react-vk/module/Playlist'>;
}
declare module 'react-vk/module/Poll.js' {
  declare module.exports: $Exports<'react-vk/module/Poll'>;
}
declare module 'react-vk/module/Post.js' {
  declare module.exports: $Exports<'react-vk/module/Post'>;
}
declare module 'react-vk/module/Recommended.js' {
  declare module.exports: $Exports<'react-vk/module/Recommended'>;
}
declare module 'react-vk/module/Subscribe.js' {
  declare module.exports: $Exports<'react-vk/module/Subscribe'>;
}
declare module 'react-vk/module/VK.js' {
  declare module.exports: $Exports<'react-vk/module/VK'>;
}
declare module 'react-vk/module/VKContext.js' {
  declare module.exports: $Exports<'react-vk/module/VKContext'>;
}
declare module 'react-vk/module/vkPropTypes.js' {
  declare module.exports: $Exports<'react-vk/module/vkPropTypes'>;
}
