// flow-typed signature: 714e0c20c65fbf75ca6f8e35a9398ab7
// flow-typed version: <<STUB>>/styled-system_v^3.0.2/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-system/dist/all' {
  declare module.exports: any;
}

declare module 'styled-system/dist/css' {
  declare module.exports: any;
}

declare module 'styled-system/dist/index' {
  declare module.exports: any;
}

declare module 'styled-system/dist/mixed' {
  declare module.exports: any;
}

declare module 'styled-system/dist/space' {
  declare module.exports: any;
}

declare module 'styled-system/dist/styles' {
  declare module.exports: any;
}

declare module 'styled-system/dist/util' {
  declare module.exports: any;
}

declare module 'styled-system/dist/variant' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-system/dist/all.js' {
  declare module.exports: $Exports<'styled-system/dist/all'>;
}
declare module 'styled-system/dist/css.js' {
  declare module.exports: $Exports<'styled-system/dist/css'>;
}
declare module 'styled-system/dist/index.js' {
  declare module.exports: $Exports<'styled-system/dist/index'>;
}
declare module 'styled-system/dist/mixed.js' {
  declare module.exports: $Exports<'styled-system/dist/mixed'>;
}
declare module 'styled-system/dist/space.js' {
  declare module.exports: $Exports<'styled-system/dist/space'>;
}
declare module 'styled-system/dist/styles.js' {
  declare module.exports: $Exports<'styled-system/dist/styles'>;
}
declare module 'styled-system/dist/util.js' {
  declare module.exports: $Exports<'styled-system/dist/util'>;
}
declare module 'styled-system/dist/variant.js' {
  declare module.exports: $Exports<'styled-system/dist/variant'>;
}
