// flow-typed signature: 723c4176d1686c223df8143a44d3b37c
// flow-typed version: <<STUB>>/transliteration_v^1.6.5/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transliteration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transliteration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transliteration/dist/node/node' {
  declare module.exports: any;
}

declare module 'transliteration/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'transliteration/lib/browser/transliteration' {
  declare module.exports: any;
}

declare module 'transliteration/lib/browser/transliteration.min' {
  declare module.exports: any;
}

declare module 'transliteration/lib/node/index' {
  declare module.exports: any;
}

declare module 'transliteration/lib/node/slugify' {
  declare module.exports: any;
}

declare module 'transliteration/lib/node/transliterate' {
  declare module.exports: any;
}

declare module 'transliteration/lib/node/utils' {
  declare module.exports: any;
}

declare module 'transliteration/src/bin/slugify' {
  declare module.exports: any;
}

declare module 'transliteration/src/bin/transliterate' {
  declare module.exports: any;
}

declare module 'transliteration/src/main/browser' {
  declare module.exports: any;
}

declare module 'transliteration/src/main/index' {
  declare module.exports: any;
}

declare module 'transliteration/src/main/slugify' {
  declare module.exports: any;
}

declare module 'transliteration/src/main/transliterate' {
  declare module.exports: any;
}

declare module 'transliteration/src/main/utils' {
  declare module.exports: any;
}

declare module 'transliteration/test/browser/slugify' {
  declare module.exports: any;
}

declare module 'transliteration/test/browser/transliterate' {
  declare module.exports: any;
}

declare module 'transliteration/test/node/slugify' {
  declare module.exports: any;
}

declare module 'transliteration/test/node/transliterate' {
  declare module.exports: any;
}

declare module 'transliteration/test/node/utils' {
  declare module.exports: any;
}

declare module 'transliteration/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transliteration/dist/node/node.js' {
  declare module.exports: $Exports<'transliteration/dist/node/node'>;
}
declare module 'transliteration/gulpfile.babel.js' {
  declare module.exports: $Exports<'transliteration/gulpfile.babel'>;
}
declare module 'transliteration/lib/browser/transliteration.js' {
  declare module.exports: $Exports<'transliteration/lib/browser/transliteration'>;
}
declare module 'transliteration/lib/browser/transliteration.min.js' {
  declare module.exports: $Exports<'transliteration/lib/browser/transliteration.min'>;
}
declare module 'transliteration/lib/node/index.js' {
  declare module.exports: $Exports<'transliteration/lib/node/index'>;
}
declare module 'transliteration/lib/node/slugify.js' {
  declare module.exports: $Exports<'transliteration/lib/node/slugify'>;
}
declare module 'transliteration/lib/node/transliterate.js' {
  declare module.exports: $Exports<'transliteration/lib/node/transliterate'>;
}
declare module 'transliteration/lib/node/utils.js' {
  declare module.exports: $Exports<'transliteration/lib/node/utils'>;
}
declare module 'transliteration/src/bin/slugify.js' {
  declare module.exports: $Exports<'transliteration/src/bin/slugify'>;
}
declare module 'transliteration/src/bin/transliterate.js' {
  declare module.exports: $Exports<'transliteration/src/bin/transliterate'>;
}
declare module 'transliteration/src/main/browser.js' {
  declare module.exports: $Exports<'transliteration/src/main/browser'>;
}
declare module 'transliteration/src/main/index.js' {
  declare module.exports: $Exports<'transliteration/src/main/index'>;
}
declare module 'transliteration/src/main/slugify.js' {
  declare module.exports: $Exports<'transliteration/src/main/slugify'>;
}
declare module 'transliteration/src/main/transliterate.js' {
  declare module.exports: $Exports<'transliteration/src/main/transliterate'>;
}
declare module 'transliteration/src/main/utils.js' {
  declare module.exports: $Exports<'transliteration/src/main/utils'>;
}
declare module 'transliteration/test/browser/slugify.js' {
  declare module.exports: $Exports<'transliteration/test/browser/slugify'>;
}
declare module 'transliteration/test/browser/transliterate.js' {
  declare module.exports: $Exports<'transliteration/test/browser/transliterate'>;
}
declare module 'transliteration/test/node/slugify.js' {
  declare module.exports: $Exports<'transliteration/test/node/slugify'>;
}
declare module 'transliteration/test/node/transliterate.js' {
  declare module.exports: $Exports<'transliteration/test/node/transliterate'>;
}
declare module 'transliteration/test/node/utils.js' {
  declare module.exports: $Exports<'transliteration/test/node/utils'>;
}
declare module 'transliteration/webpack.config.babel.js' {
  declare module.exports: $Exports<'transliteration/webpack.config.babel'>;
}
