// flow-typed signature: 04d2b374f83e35808785572320eba27a
// flow-typed version: <<STUB>>/translit_v^0.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'translit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'translit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'translit/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'translit/index' {
  declare module.exports: $Exports<'translit'>;
}
declare module 'translit/index.js' {
  declare module.exports: $Exports<'translit'>;
}
declare module 'translit/test.js' {
  declare module.exports: $Exports<'translit/test'>;
}
