// flow-typed signature: 2f060f0f03d655da79a910eb8d11756e
// flow-typed version: <<STUB>>/translit-russian_v0.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'translit-russian'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'translit-russian' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'translit-russian/index' {
  declare module.exports: $Exports<'translit-russian'>;
}
declare module 'translit-russian/index.js' {
  declare module.exports: $Exports<'translit-russian'>;
}
