// flow-typed signature: f5b5e55f233a3e703d6d89060d888c6d
// flow-typed version: <<STUB>>/vk-io_v^4.0.0-rc.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vk-io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vk-io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vk-io/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vk-io/lib/index.js' {
  declare module.exports: $Exports<'vk-io/lib/index'>;
}
