export { default as FacebookSquareIcon } from './facebook-square-icon';
export { default as FacebookIcon } from './facebook-icon';
export { default as InstagramIcon } from './instagram-icon';
export { default as TwitterIcon } from './twitter-icon';
export { default as VkIcon } from './vk-icon';
export { default as VkWipIcon } from './vk-wip-icon';
export { default as YoutubeIcon } from './youtube-icon';
export { default as GooglePlusIcon } from './google-plus-icon';
export { default as GithubIcon } from './github-icon';
